[workspace]
resolver = "2"
members = [ "pumpkin-entity", "pumpkin-inventory", "pumpkin-macros/", "pumpkin-protocol/", "pumpkin-registry/", "pumpkin-world", "pumpkin/" ]

[workspace.package]
version = "0.1.0"
edition = "2021"

[profile.release]
debug = 1
lto = true
codegen-units = 1

[workspace.dependencies]
tokio = { version = "1.39.3", features = ["net", "macros", "rt-multi-thread", "fs", "io-util"] }
rayon = "1.10.0"
