[package]
name = "pumpkin"
version = "0.1.0-dev"
description = "Empowering everyone to host fast and efficient Minecraft servers."
edition = "2021"

[features]
default = []
dhat-heap = ["dhat"]

[dependencies]
# memory analysis
dhat = { version = "0.3.3", optional = true }

# pumpkin
pumpkin-text = { path = "../pumpkin-text" }
pumpkin-inventory = { path = "../pumpkin-inventory"}
pumpkin-world = { path = "../pumpkin-world"}
pumpkin-entity = { path = "../pumpkin-entity"}
pumpkin-protocol = { path = "../pumpkin-protocol"}
pumpkin-registry = { path = "../pumpkin-registry"}

# config
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8.19"

bytes = "1.7"

rand = "0.8.5"

num-traits = "0.2"
num-derive = "0.4"
num-bigint = "0.4.6"

# encryption
rsa = "0.9.6"
rsa-der = "0.3.0"

# authentication
reqwest = { version = "0.12.5", features = ["json"]}

sha1 = "0.10.6"
digest = "=0.11.0-pre.9"

# velocity en
hmac = "0.12.1"
sha2 = "0.10.8"

thiserror = "1.0.63"

# icon loading
base64 = "0.22.1"
image = { version = "0.25", default-features = false, features = ["png"]}

# logging
simple_logger = "5.0.0"
log = "0.4"

# networking
crossbeam-channel = "0.5.13"

uuid = { version = "1.10", features = ["serde", "v3"]}

tokio.workspace = true
rayon.workspace = true
